AWSTemplateFormatVersion: 2010-09-09


Mappings:
  MyEnvMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small

Parameters:
  KeyPairParameter:
    Description: Take KeyName as parameter
    Type: AWS::EC2::KeyPair::KeyName
  EnvParameter:
    Description: Select env from list
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  MyEIPProd: !Equals [!Ref EnvParameter, prod]
  CreateSecurityGroup: !Equals [!Ref EnvParameter, dev]
        

Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0cc87e5027adcdca8
      InstanceType: !FindInMap
        - MyEnvMap
        - !Ref EnvParameter
        - instanceType
      KeyName: !Ref KeyPairParameter
      SecurityGroups: !If [CreateSecurityGroup, [!Ref SSHSecureGrp], !Ref 'AWS::NoValue']

  SSHSecureGrp:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateSecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 

  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: MyEIPProd
    Properties:
      InstanceId: !Ref DevEC2Instance              